## 8-bindings.conf

# Shift windows around 
bindsym $mod+Shift+less move workspace to output left
bindsym $mod+Shift+greater move workspace to output right
bindsym $mod+Ctrl+less move workspace to output down
bindsym $mod+Ctrl+greater move workspace to output up

# Pulse Audio controls
bindsym XF86AudioRaiseVolume exec "amixer -q sset Master,0 5%+ unmute; notify-send -t 500 `amixer get Master | grep -m1 -oE [0-9]+%`"
bindsym XF86AudioLowerVolume exec "amixer -q sset Master,0 5%- unmute; notify-send -t 500 `amixer get Master | grep -m1 -oE [0-9]+%`"
bindsym XF86AudioMute exec "amixer -q sset Master,0 toggle"

# Switch to workspace
bindsym $mod+1 workspace $workspace1
bindsym $mod+2 workspace $workspace2
bindsym $mod+3 workspace $workspace3
bindsym $mod+4 workspace $workspace4
bindsym $mod+5 workspace $workspace5
bindsym $mod+6 workspace $workspace6
bindsym $mod+7 workspace $workspace7
bindsym $mod+8 workspace $workspace8
bindsym $mod+9 workspace $workspace9
bindsym $mod+0 workspace $workspace10

# Move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $workspace1; workspace $workspace1; focus
bindsym $mod+Shift+2 move container to workspace $workspace2; workspace $workspace2; focus
bindsym $mod+Shift+3 move container to workspace $workspace3; workspace $workspace3; focus
bindsym $mod+Shift+4 move container to workspace $workspace4; workspace $workspace4; focus
bindsym $mod+Shift+5 move container to workspace $workspace5; workspace $workspace5; focus
bindsym $mod+Shift+6 move container to workspace $workspace6; workspace $workspace6; focus
bindsym $mod+Shift+7 move container to workspace $workspace7; workspace $workspace7; focus
bindsym $mod+Shift+8 move container to workspace $workspace8; workspace $workspace8; focus
bindsym $mod+Shift+9 move container to workspace $workspace9; workspace $workspace9; focus
bindsym $mod+Shift+0 move container to workspace $workspace10; workspace $workspace10; focus

# Start a terminal in the terminals workspace
bindsym $mod+Return exec alacritty; workspace $workspace3

# Kill focused window
bindsym $mod+Shift+q kill

# Lock screen
bindsym Mod4+l exec "i3lock-fancy -p -g"

# Launch menu
bindsym $mod+d exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show drun -show-icons'

# Change focus
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Move focused window
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# Split in horizontal orientation
bindsym $mod+Shift+v split h

# Split in vertical orientation
bindsym $mod+v split v

# Enter fullscreen mode for focused container
bindsym $mod+f fullscreen toggle

# Change container layout (stacked, tabbed, toggle split)
bindsym $mod+q layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# Toggle floating for focused window
bindsym $mod+Shift+space floating toggle

# Change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# Focus the parent container
bindsym $mod+a focus parent

# Focus the child container
bindsym $mod+Shift+a focus child

# Reload the configuration file
bindsym $mod+Shift+c reload

# Restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# Exit i3 (logs you out of your X session)
bindsym $mod+Shift+E exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# Resize windows
bindsym $mod+r mode "resize"
